# infra/template.yml
AWSTemplateFormatVersion: '2010-09-09'
Description: Two .NET 8 Lambdas communicating through SQS

Parameters:
  ArtifactBucket:
    Type: String

Resources:

  MainQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: app-main-queue

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: app-main-dlq

  ProducerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: producer-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: ProducerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt MainQueue.Arn

  ConsumerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: consumer-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: ConsumerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt MainQueue.Arn

  ProducerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: producer-lambda
      Runtime: dotnet8
      MemorySize: 512
      Timeout: 30
      Role: !GetAtt ProducerRole.Arn
      Handler: ProducerLambda::ProducerLambda.Function::FunctionHandler
      Environment:
        Variables:
          QUEUE_URL: !Ref MainQueue
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: producer.zip

  ConsumerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: consumer-lambda
      Runtime: dotnet8
      MemorySize: 512
      Timeout: 30
      Role: !GetAtt ConsumerRole.Arn
      Handler: ConsumerLambda::ConsumerLambda.Function::FunctionHandler
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: consumer.zip

  QueueTrigger:
    Type: AWS::Lambda::EventSourceMapping
    DependsOn: ConsumerLambda
    Properties:
      EventSourceArn: !GetAtt MainQueue.Arn
      FunctionName: !Ref ConsumerLambda
      BatchSize: 10
      Enabled: true

Outputs:
  QueueUrl:
    Value: !Ref MainQueue