AWSTemplateFormatVersion: '2010-09-09'
Description: SQS + 2 Lambdas

Resources:

  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: app-main-queue

  ProducerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: ProducerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: "*"

  ConsumerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: ConsumerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: "*"

  ProducerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: producer-lambda
      Runtime: dotnet8
      Handler: ProducerLambda::ProducerLambda.Function::FunctionHandler
      Role: !GetAtt ProducerRole.Arn
      Code:
        ZipFile: |
          placeholder

  ConsumerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: consumer-lambda
      Runtime: dotnet8
      Handler: ConsumerLambda::ConsumerLambda.Function::FunctionHandler
      Role: !GetAtt ConsumerRole.Arn
      Code:
        ZipFile: |
          placeholder

  QueueTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt Queue.Arn
      FunctionName: !Ref ConsumerLambda
      BatchSize: 10
      Enabled: true