# .github/workflows/deploy.yml
name: CI-CD AWS Lambdas

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    environment: Main

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install SonarScanner
        shell: powershell
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$env:USERPROFILE\.dotnet\tools" | Out-File -Append -FilePath $env:GITHUB_PATH

      - name: Sonar Begin
        shell: powershell
        run: |
          dotnet-sonarscanner begin `
            /k:"MsbowElite_serverless-csharp-sqs" `
            /o:"lucasrsena" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.host.url="https://sonarcloud.io"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Sonar End
        shell: powershell
        run: |
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Publish Producer
        shell: powershell
        run: |
          dotnet publish .\src\ProducerLambda `
            -c Release `
            -o publish\producer `
            /p:PublishReadyToRun=false

          Compress-Archive -Path publish\producer\* -DestinationPath producer.zip -Force

      - name: Publish Consumer
        shell: powershell
        run: |
          dotnet publish .\src\ConsumerLambda `
            -c Release `
            -o publish\consumer `
            /p:PublishReadyToRun=false

          Compress-Archive -Path publish\consumer\* -DestinationPath consumer.zip -Force

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Artifacts to S3
        shell: powershell
        run: |
          aws s3 cp producer.zip s3://${{ secrets.ARTIFACT_BUCKET }}/producer.zip
          aws s3 cp consumer.zip s3://${{ secrets.ARTIFACT_BUCKET }}/consumer.zip

      - name: Validate CloudFormation
        shell: powershell
        run: |
          aws cloudformation validate-template `
            --template-body file://infra/template.yml

      - name: Deploy CloudFormation
        shell: powershell
        run: |
          aws cloudformation deploy `
            --stack-name sqs-lambda-stack `
            --template-file infra/template.yml `
            --capabilities CAPABILITY_NAMED_IAM `
            --parameter-overrides ArtifactBucket=${{ secrets.ARTIFACT_BUCKET }}

      - name: Show Stack Events on Failure
        if: failure()
        shell: powershell
        run: |
          $exists = aws cloudformation list-stacks `
            --stack-status-filter CREATE_FAILED CREATE_IN_PROGRESS ROLLBACK_COMPLETE ROLLBACK_FAILED UPDATE_ROLLBACK_FAILED UPDATE_ROLLBACK_COMPLETE `
            --query "StackSummaries[?StackName=='sqs-lambda-stack'].StackName" `
            --output text

          if ($exists -eq "sqs-lambda-stack") {
            aws cloudformation describe-stack-events `
              --stack-name sqs-lambda-stack `
              --max-items 30
          }