name: CI-CD AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  build-analyze-deploy:
    runs-on: windows-latest
    environment: Main

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Cache Sonar Packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar

      - name: Install Sonar Scanner
        shell: powershell
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$env:USERPROFILE\.dotnet\tools" | Out-File -Append -FilePath $env:GITHUB_PATH

      - name: Restore
        run: dotnet restore

      - name: Sonar Begin
        shell: powershell
        run: |
          dotnet-sonarscanner begin `
            /k:"MsbowElite_serverless-csharp-sqs" `
            /o:"lucasrsena" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.host.url="https://sonarcloud.io"

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Sonar End
        shell: powershell
        run: |
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation
        shell: powershell
        run: |
          aws cloudformation deploy `
            --stack-name sqs-lambda-stack `
            --template-file infra/template.yml `
            --capabilities CAPABILITY_NAMED_IAM